Cleanup of bsess()
Also move the setting of PROMPT_COMMAND on new sessions.

Signed-off-by: Stephen L Jones <sljones@slohj.org>

diff --git a/bash-session b/bash-session
--- a/bash-session
+++ b/bash-session
@@ -42,14 +42,14 @@ declare -g _bs_name
 bsess ()
 {
     # Error check, there should be only 0 or one parameters.
-    if [[ -n "${2}" ]]
+    if (( ${#} > 1 ))
     then
         # FIXME:
         # Error message needed: bad usage!
         return 1
     fi
 
-    if [[ -z "${1}" ]]
+    if (( ${#} == 0 ))
     then
         # Print the current session if it has already been set.
         if [[ -n "${_bs_name}" ]]
@@ -72,15 +72,43 @@ bsess ()
         # Restore the original state of nullglob.
         ${globsetting}
     else
-        _bs_name="${1}"
-        # Source the session file if it exists.
-        if [[ -f "${HOME}/.bash_session_${_bs_name}" ]]
+        if [[ -n "${1}" ]]
         then
-            . "${HOME}/.bash_session_${_bs_name}"
+            # TODO
+            # What should we do if a session has already been set?
+            # Should we just go on our merry way no matter what, or should we
+            # disallow changing from the current session to an existing one and
+            # only allow creation of a new session, i.e. copying to a new
+            # session.
+            _bs_name="${1}"
+            # Source the session file if it exists.
+            if [[ -f "${HOME}/.bash_session_${_bs_name}" ]]
+            then
+                . "${HOME}/.bash_session_${_bs_name}"
+            else
+                HISTFILE="${HOME}/.bash_history_${_bs_name}"
+                # Set PROMPT_COMMAND
+                if [[ -v PROMPT_COMMAND ]]
+                then
+                    # The user is already using PROMPT_COMMAND for something else, so just turn
+                    # it into a compound command.
+                    PROMPT_COMMAND="${PROMPT_COMMAND}; _bs_set_stitle"
+                else
+                    PROMPT_COMMAND="_bs_set_stitle"
+                fi
+
+            fi
         else
-            HISTFILE="${HOME}/.bash_history_${_bs_name}"
+            # TODO
+            # Should we do something else with a set but empty ${1}, like just
+            # unset the session name? But without knowing what the original
+            # history file was this becomes an unknown state.  See the above
+            # TODO for more questions.
+            printf "cannot undo a session\n" >&2
+            return 1
         fi
     fi
+    return 0
 }
 
 # Write out the session information do disk.
@@ -214,16 +242,6 @@ _bs_vars_unset ()
 }
 
 # Execute on load commands
-
-# Set PROMPT_COMMAND
-if [[ -v PROMPT_COMMAND ]]
-then
-    # The user is already using PROMPT_COMMAND for something else, so just turn
-    # it into a compound command.
-    PROMPT_COMMAND="${PROMPT_COMMAND}; _bs_set_stitle"
-else
-    PROMPT_COMMAND="_bs_set_stitle"
-fi
 
 # Vim mode line {{{1
 # vim: expandtab softtabstop=4 shiftwidth=4 filetype=sh:
